inherit_from: '.rubocop_todo.yml'

Style/AsciiComments:
  Enabled: false

Style/BlockDelimiters:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: true

Style/MutableConstant:
  Enabled: false

Metrics/AbcSize:
  Max: 50

Metrics/BlockLength:
  Enabled: false

Metrics/ClassLength:
  Max: 200

Metrics/CyclomaticComplexity:
  Exclude:
    - lib/kirico/csv_generator.rb
    - lib/kirico/validators/sjis_bytesize_validator.rb

Metrics/LineLength:
  Max: 200
  Exclude:
    - 'kirico.gemspec'

Metrics/MethodLength:
  Enabled: false
